#pragma config(Sensor, port1,  gyro,           sensorVexIQ_Gyro)
#pragma config(Sensor, port3,  color,          sensorVexIQ_ColorGrayscale)
#pragma config(Motor,  motor4,          leftWheels,    tmotorVexIQ, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motor7,          hDrive,        tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor8,          armLow,        tmotorVexIQ, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motor10,          armHigh,       tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor12,         rightWheels,   tmotorVexIQ, PIDControl, reversed, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void printValues(int gyroReading, int colorReading, int lx, int ly, int ry)
{
	displayTextLine(0, "gyro = %d", gyroReading);
	displayTextLine(1, "color = %d", colorReading);
	displayTextLine(2, "lX = %d", lx);
	displayTextLine(3, "lY = %d", ly);
	displayTextLine(4, "rY = %d", ry);
}

task main()
{
	const int THRESHOLD = 10;
	const int HDRIVEMAX = 100;

	resetGyro(gyro);
	repeat(forever)
	{
		int leftJoystickY;
		int leftJoystickX;
		int rightJoystickY;
		bool lUp;
		bool lDown;
		bool rUp;
		bool rDown;
		int hDriveSpeed;
		int leftSpeed;
		int rightSpeed;
		int lowArmSpeed;
		int highArmSpeed;

		// First Step: This is where we retrieve all the joystick, button, and sensor values we will need

		leftJoystickY = getJoystickValue(ChA);
		leftJoystickX = getJoystickValue(ChB);
		rightJoystickY = getJoystickValue(ChD);
		lUp = (getJoystickValue(BtnLUp) == 1);
		lDown = (getJoystickValue(BtnLDown) == 1);
		rUp = (getJoystickValue(BtnRUp) == 1);
		rDown = (getJoystickValue(BtnRDown) == 1);

		// Second Step: This is where we calculate what we need to set each of the motor speeds to

		if (leftJoystickX < THRESHOLD && leftJoystickX > -THRESHOLD)
		{
			leftJoystickX = 0;
		}

		if (leftJoystickY < THRESHOLD && leftJoystickY > -THRESHOLD)
		{
			leftJoystickY = 0;
		}

		if (rightJoystickY < THRESHOLD && rightJoystickY > -THRESHOLD)
		{
			rightJoystickY = 0;
		}

		leftSpeed = (leftJoystickY + leftJoystickX)/2;
		rightSpeed = (leftJoystickY - leftJoystickX)/2;

  	if (lUp)
  	{
  		highArmSpeed = rightJoystickY;
  	}
  	else
  	{
  		highArmSpeed = 0;
  	}

  	if (lDown)
  	{
  		lowArmSpeed = rightJoystickY;
  	}
  	else
  	{
  		lowArmSpeed = 0;
  	}

  	if (rUp)
  	{
  		hDriveSpeed = HDRIVEMAX;
  	}
  	else if (rDown)
  	{
  		hDriveSpeed = -HDRIVEMAX;
  	}
  	else
  	{
  		hDriveSpeed = 0;
  	}

	  // Third Step: This is where we set all the motor speeds to what they should be

	  setMotorSpeed(leftWheels, leftSpeed);
	  setMotorSpeed(rightWheels, rightSpeed);
	  setMotorSpeed(hDrive, hDriveSpeed);
		setMotorSpeed(armHigh, highArmSpeed);
		setMotorSpeed(armLow, lowArmSpeed);

		sleep(75);
		printValues(getGyroDegrees(gyro)%360, getColorGrayscale(color), leftJoystickX, leftJoystickY, rightJoystickY);
	}


}
