#pragma config(Sensor, port12, gyro,           sensorVexIQ_Gyro)
#pragma config(Motor,  motor3,          hDrive,        tmotorNone, openLoop)
#pragma config(Motor,  motor4,          leftWheels,    tmotorVexIQ, PIDControl, reversed, driveLeft, encoder)
#pragma config(Motor,  motor5,          rightWheels,   tmotorVexIQ, PIDControl, driveRight, encoder)
#pragma config(Motor,  motor6,          arm,           tmotorVexIQ, PIDControl, reversed, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void printGyroPosition() {
	displayTextLine(0, "gyro = %d", getGyroDegrees(gyro)%360);
}

task main()
{
	resetGyro(gyro);
	repeat(forever) {
		int threshold = 10;
		int leftJoystickY;
		int leftJoystickX;
		int rightJoystickY;
		int leftSpeed;
		int rightSpeed;

		leftJoystickY = getJoystickValue(ChA);
		leftJoystickX = getJoystickValue(ChB);
		rightJoystickY = getJoystickValue(ChD);

		leftSpeed = (leftJoystickY + leftJoystickX)/2;
		rightSpeed = (leftJoystickY - leftJoystickX)/2;

		if(leftSpeed > threshold || leftSpeed < -threshold)
		{
			setMotorSpeed(leftWheels, leftSpeed);
		}
		else
		{
			setMotorSpeed(leftWheels, 0);
		}

		if(rightSpeed > threshold || rightSpeed < -threshold)
		{
			setMotorSpeed(rightWheels, rightSpeed);
		}
		else
		{
			setMotorSpeed(rightWheels, 0);
		}

		if(rightJoystickY > threshold || rightJoystickY < -threshold)
		{
			setMotorSpeed(arm, rightJoystickY);
		}
		else
		{
			setMotorSpeed(arm, 0);
		}

		if(getJoystickValue(BtnLUp) == 1) { setMotorSpeed(hDrive, 100); }
		else if(getJoystickValue(BtnLDown) == 1) { setMotorSpeed(hDrive, -100); }
		else { setMotorSpeed(hDrive, 0); }



		sleep(75);
		printGyroPosition();
	}


}
