#pragma config(Motor,  motor4,          leftWheels,    tmotorVexIQ, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motor12,         rightWheels,   tmotorVexIQ, PIDControl, reversed, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define TEST_MODE

#ifdef TEST_MODE
#define PRINT_TO_SCRN(x, y) printValues(x, y)
#else
#define PRINT_TO_SCRN(x, y)
#endif

void printValues(int left, int right)
{
	displayTextLine(0, "leftArm = %d", left);
	displayTextLine(1, "rightArm = %d", right);
}

/*void setLEDColor(bool tank) {
	if(tank) {
		setTouchLEDRGB(touch, 84, 122, 138);
	}
	else {
		setTouchLEDRGB(touch, 255, 177, 82);
	}
}*/

task main()
{
	const int THRESHOLD = 15;
	const int HDRIVEMAX = 60;
	bool tankMode = true;
	int touchCooldown = 0;

	setMotorEncoderUnits(encoderCounts);
//	setLEDColor(tankMode);

	//resetGyro(gyro);
	repeat(forever)
	{
		int leftJoystickY;
		int leftJoystickX;
		int rightJoystickY;
		bool lUp;
		bool lDown;
		bool rUp;
		bool rDown;
		int hDriveSpeed;
		int leftSpeed;
		int rightSpeed;
		int armSpeed;

		// First Step: This is where we retrieve all the joystick, button, and sensor values we will need

		leftJoystickY = getJoystickValue(ChA);
		leftJoystickX = getJoystickValue(ChB);
		if (leftJoystickX < THRESHOLD && leftJoystickX > -THRESHOLD)
		{
			leftJoystickX = 0;
		}

		if (leftJoystickY < THRESHOLD && leftJoystickY > -THRESHOLD)
		{
			leftJoystickY = 0;
		}

		if (rightJoystickY < THRESHOLD && rightJoystickY > -THRESHOLD)
		{
			rightJoystickY = 0;
		}


				leftSpeed = round( ( leftJoystickY + leftJoystickX ) / 1.5 );
				rightSpeed = round( ( leftJoystickY - leftJoystickX ) / 1.5 );


  

	  setMotorSpeed(leftWheels, leftSpeed);
	  setMotorSpeed(rightWheels, rightSpeed);

		sleep(75);
	}


}
