#pragma config(Sensor, port8, color,          sensorVexIQ_ColorGrayscale)
#pragma config(Sensor, port6, gyro,           sensorVexIQ_Gyro)
#pragma config(Motor,  motor1,          leftWheels,    tmotorVexIQ, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motor7,          rightWheels,   tmotorVexIQ, PIDControl, reversed, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void printGyroPosition() {
	displayTextLine(0, "gyro = %d", getGyroDegrees(gyro)%360);
}

void printColorSensor() {
	displayTextLine(1, "color = %d", getColorGrayscale(color));
}

task main()
{
	resetGyro(gyro);
	repeat(forever) {
		int threshold = 10;
		int leftJoystickY;
		int leftJoystickX;
		int leftSpeed;
		int rightSpeed;

		leftJoystickY = getJoystickValue(ChA);
		leftJoystickX = getJoystickValue(ChB);

		leftSpeed = (leftJoystickY + leftJoystickX);
		rightSpeed = (leftJoystickY - leftJoystickX);

		if(leftSpeed > threshold || leftSpeed < -threshold)
		{
			setMotorSpeed(leftWheels, leftSpeed);
		}
		else
		{
			setMotorSpeed(leftWheels, 0);
		}

		if(rightSpeed > threshold || rightSpeed < -threshold)
		{
			setMotorSpeed(rightWheels, rightSpeed);
		}
		else
		{
			setMotorSpeed(rightWheels, 0);
		}

		sleep(75);
		printGyroPosition();
		printColorSensor();
	}


}
